### ISSUE TITLE
Processing with Ernie sample from Simbnibs fails

### ISSUE THREAD

**Issue by spichardo** [ProteusMRIgHIFU/BabelBrain#24]
Curiously enough, we have tested with dozens of Simnibs 4 charm's tool output with no issues but the one in the example dataset of https://simnibs.github.io/simnibs/build/html/dataset.html fails... it seems the surface extraction of the available mask produces invalid surface meshes that later causes issues , it fails during voxelization step.
Thanks @devbanu for spotting this.
```
--Babel-Brain-Low-Error
Traceback (most recent call last):
  File "CalculateMaskProcess.py", line 73, in CalculateMaskProcess
  File "BabelDatasetPreps.py", line 337, in GetSkullMaskFromSimbNIBSSTL
  File "GPUVoxelize/Voxelize.py", line 450, in Voxelize
  File "trimesh/caching.py", line 109, in get_cached
    value = function(*args, **kwargs)
  File "trimesh/scene/scene.py", line 454, in triangles
    self._cache['triangles_node'] = np.hstack(triangles_node)
  File "<__array_function__ internals>", line 180, in hstack
  File "numpy/core/shape_base.py", line 345, in hstack
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by spichardo** [comment]
fixed at 8ae5947823b62b30a7754d2a230c7bbd32705586
